from django import forms
from .models import *
class UserForm(forms.Form):
    name = forms.CharField()
    age = forms.IntegerField()


class AnswersForm(forms.Form):
    name = forms.CharField(max_length=20)
    surname = forms.CharField(max_length=30)
    group = forms.CharField(max_length=20)
    var = forms.IntegerField()
    a1 = forms.CharField(max_length=50)
    a2 = forms.CharField(max_length=50)
    a3 = forms.CharField(max_length=50)
    a4 = forms.CharField(max_length=50)
    a5 = forms.CharField(max_length=50)
    a6 = forms.CharField(max_length=50)
    a7 = forms.CharField(max_length=50)
    a8 = forms.CharField(max_length=50)
    a9 = forms.CharField(max_length=50)
    a10 = forms.CharField(max_length=50)
    a11 = forms.CharField(max_length=50)
    a12 = forms.CharField(max_length=50)
    a13 = forms.CharField(max_length=50)
    a14 = forms.CharField(max_length=50)
    a15 = forms.CharField(max_length=50)
    a16 = forms.CharField(max_length=50)
    a17 = forms.CharField(max_length=50)
    a18 = forms.CharField(max_length=50)
    a19 = forms.CharField(max_length=50)
    a20 = forms.CharField(max_length=50)
    a21 = forms.CharField(max_length=50)
    a22 = forms.CharField(max_length=50)
    a23 = forms.CharField(max_length=50)
    a24 = forms.CharField(max_length=50)
    a25 = forms.CharField(max_length=50)
    a26 = forms.CharField(max_length=50)
    a27 = forms.CharField(max_length=50)
    a28 = forms.CharField(max_length=50)
    a29 = forms.CharField(max_length=50)
    a30 = forms.CharField(max_length=50)
    a31 = forms.CharField(max_length=50)
    a32 = forms.CharField(max_length=50)
    a33 = forms.CharField(max_length=50)
    a34 = forms.CharField(max_length=50)
    a35 = forms.CharField(max_length=50)
    a36 = forms.CharField(max_length=50)
    a37 = forms.CharField(max_length=50)
    a38 = forms.CharField(max_length=50)
    a39 = forms.CharField(max_length=50)
    a40 = forms.CharField(max_length=50)
    points = forms.CharField(max_length=200)
    result = forms.IntegerField()
    task1 = forms.IntegerField()
    task2 = forms.IntegerField()
    task3 = forms.IntegerField()
    task4 = forms.IntegerField()